seed: 5
#----change to your own dataset path----#
dataset_path: ../UVG/honeybee

dataset_type: all 
model:
  model_name: D_NeRV
  act: gelu
  stride_list: [[5,5],[4,4],[4,4],[3,3],[2,2]] 
  kernel_list: [1, 3, 5, 5, 5]
  padding_list: [0, 1, 2, 2, 2]
  encoder_list: [5, 4, 4, 3, 2]
  diff_enc_list: [[3,4], [3,3], [3,2]]
  diff_dec_kernel: [3, 3, 3]
  diff_dec_stride: [[4,4]]
  diff_dec_padding: [1,1,1]
  conv_type: conv
  c1: 64
  d: 16
  c2: 92 
  height: 1080
  width: 1920
train_batchsize: 1
val_batchsize: 1
workers: 4
epoch: 300

optim:
  optim_type: Adam
  lr: 0.0005
  beta1: 0.5
  beta2: 0.999
  lr_schedule: warmup_cosine
  lr_point: 0.2

loss: L2
print_freq: 50
eval_freq: 50

